<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpeA7vb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpeA7vb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXpeA7vb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXpeA7vb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXpeA7vb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XpeA7vb',
    'container.build_id' => '6b6dd7eb',
    'container.build_time' => 1574696271,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpeA7vb');
