<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJIaxtY8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJIaxtY8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJIaxtY8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJIaxtY8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJIaxtY8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JIaxtY8',
    'container.build_id' => '89acf9fd',
    'container.build_time' => 1574699793,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJIaxtY8');
